### ISSUE TITLE
Why these servers asks Chrome ?

### ISSUE THREAD

**Issue by willemijns** [librespeed/speedtest#293]
Hello,

On https://www.rdcohelp.com/speedtest/ we can see 
"Please use Google Chrome for this test"
Same thing for https://www.iptp.net/en_US/iptp-tools/bandwidth-test/
Why ?

**Comment by adolfintel** [comment]
Those are both based on very old versions of LibreSpeed, they have compatibility issues with some versions of Edge.

**Comment by adolfintel** [comment]
One of them is based on a very old version of LibreSpeed, which had compatibility issues on some versions of Edge, the other has no reason to recommend Chrome, unless there's something weird on their servers that creates problems to other browsers.
LibreSpeed supports all major browsers, the ping test tends to be more accurate on chromium-based browsers though, because of how timing is implemented internally to the browser (you can only notice the difference on connections with very low ping)
