### ISSUE TITLE
centos

### ISSUE THREAD

**Issue by liuguoqing0929** [librespeed/speedtest#304]
Your dockerfile belongs to ubuntu, can you provide a centos file

**Comment by maddie** [comment]
I don't mean to be rude, but please learn how to write an issue first. We have no way to help you if you're just describing pieces of information right off of your head.

You have opened several issues already with no helpful description of what you're trying to do, under what environment, and what the actual problem is. We have been patient enough to "guess" what you're trying to say. But still, we have no idea what you're trying to achieve here.

The `Dockerfile` you're mentioning doesn't "belong" to any OS. Docker should be OS agnostic, you can build it as long as you have Docker installed (I can build it on my Mac even). It pulls the Ubuntu image as a base and installs the packages onto the Ubuntu image (overlay). Please learn about how Docker works before you post an issue like this.

From now on all issues like this will be closed without further responses.
