### ISSUE TITLE
Why discard first pong in pingTest

### ISSUE THREAD

**Issue by kodaihirano** [librespeed/speedtest#341]
## Description
I think the first "instspd" is no difference from the follows, so  it doesn't need to discard the first pong in pingTest.
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L608
This will reset here
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L602

Do you discard the first response, because it tends to late? If so, just remove L608.

## Why it should be implemented
Not to waste test time.

## Optional: implementation suggestions
remove https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L607-L609
and https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L636
modify
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L628
to
`if (i === 0) ping = instspd;`
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L631
to
`if (i === 1) jitter = instjitter;`

**Comment by adolfintel** [comment]
To understand why the first pong is discarded, you have to understand how TCP and persistent HTTP work. Basically, when you make the first request, the browser opens a connection with the server (this requires performing the TCP 3-way handshake), then sends the request and waits for the response. From now on the connection remains open as a persistent HTTP connection, and subsequent requests are sent directly without the need to do the 3-way handshake. What this means is that the first ping will be roughly 3 times higher than the actual value, and that's why we discard it.

**Comment by kodaihirano** [comment]
I understand that you discard the first response, because it tends to too late.

I'm sorry if I sound picky.
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L608
This will reset here
https://github.com/librespeed/speedtest/blob/9efae7c27c34ddf31cc95d3063775dec3f476176/speedtest_worker.js#L602
so,I think L608 should be removed.
