### ISSUE TITLE
Packet loss

### ISSUE THREAD

**Issue by esantanche** [librespeed/speedtest#355]
## Description
I can't find a packet loss measure.

## Why it should be implemented
For a good internet connection, packet loss should be less than 1%. It would be useful to see it displayed.
Sourceforge had a test that displayed packet loss. I'm looking for a replacement.

**Comment by adolfintel** [comment]
If I had a dollar for every time this was asked, I'd be Jeff Bezos right now.

Jokes aside, packet loss can't be measured over HTTP because it works over TCP, which implements reliable communication. You can detect failed requests, but you won't be able to know if an individual packet was lost and had to be retransmitted. I've seen some tests around that implement it by measuring ping spikes, I think the sourceforge one was one of them but don't quote me on that, anyway, it's unreliable and I'm not going to do it that way.

A proper packet loss test could be done with WebRTC, but that would make LibreSpeed harder to install, it wouldn't work on older browsers, and we'd probably lose the PHP backend too, not to mention that a lot of people disable WebRTC for privacy reasons. If HTTP/2 becomes more commonplace, we might be able to implement it in some hacky way, since it works over UDP, but as of now I haven't looked into it.

Hope that answers your question, sorry.

**Comment by esantanche** [comment]
Thank you very much. I will tell people to do a ping 8.8.8.8 to see packet loss.

**Comment by fiveangle** [comment]
Having an non-default option to include a separate _Upstream packet lost estimation_ via pinging a specific known host (e.g. the first  pingable upstream ISP host on our outgoing traceroute) would be a very nice addition.
