### ISSUE TITLE
Some users never get Upload speeds reported

### ISSUE THREAD

**Issue by carlos-chavez-p** [librespeed/speedtest#372]
Some users report that they never see an Upload speed reported after the test.  Only Download, Ping and Jitter have values.  Upload always at 0.  So far only about 3 clients report the problem, the rest are fine.  How can we diagnose?

## Server
Running on CentOS 7 with PHP 5.6.40 (Freepbx Distro)
Ran the tests on two different servers and the client has the same issue on both.
https://pbxoficina.telecomabmex.com/speedtest

## Client
Failed tests were done on WIndows 10 with both Chrome and Edge.

## Steps to reproduce
All results are the same on the client no matter whet browser is used.

## Expected behaviour
Most clients do report Upload and Download speeds correctly

## Screenshots
![WhatsApp Image 2020-10-22 at 12 29 26 PM](https://user-images.githubusercontent.com/73307573/96910064-88d6dd80-1464-11eb-81da-da1c4569a52f.jpeg)

**Comment by adolfintel** [comment]
Hi,
I haven't seen this one in a long time, but it is usually caused by something installed on the client: antivirus software, firewalls, VPNs, ...
If it becomes an issue, you can set `forceIE11Workaround` to true: this will use an alternate method for measuring upload speed designed for old browser and will almost certainly fix your issue, although it will be less accurate, especially at high speeds.

Btw, I can't connect to your speedtest.

If you need more help, write me at info@fdossena.com, don't use issues for troubleshooting.
