### ISSUE TITLE
Tag docker images with specific speedtest version

### ISSUE THREAD

**Issue by ondrejmo** [librespeed/speedtest#402]
## Description
I would be nice if docker images had specific version in their tags, i.e. `adolfintel/speedtest:latest` -> `adolfintel/speedtest:5.2.2`.

## Why it should be implemented
It helps with updates/rollbacks in production environment as there is no confusion about the version of speedtest included in an image, also it better adheres to the unwritten best-practice in docker images.

**Comment by callowaylc** [comment]
@ondrejmo, the repo author either chose to either purposefully diverge the development path for the docker branch (starting in 2017!!) or is just some embodiment of chaos; I was about to ask that he add links to supporting documentation in the "docker" [README](https://github.com/librespeed/speedtest/blob/docker/doc.md), and then i saw this VV.
 
![image](https://user-images.githubusercontent.com/996638/112398245-06e52c00-8d04-11eb-89ca-879bd9b56d02.png)

Which means you're ~probably~ not getting the sha/hash commit tags on the docker image repo, nor am I following up on the links, because anyone ~crazy enough~ willing to maintain divergent paths for 3+ years is not working on his "best practice" game. 

I don't know why or what business would use a speedtest in a prod env, but I personally wouldn't run with this, because you will not have any guarantees on future releases being run through any type of QAS or integration testing pipeline. 

That said, if you're in a pinch, you can use the image commit hash as a tag-like construct:
```sh
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest
$ docker run -it --rm alpine@sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be echo hello
```

`$image@sha256:$sha`

**Comment by Perflyst** [comment]
I also think the container images should be tagged with the release version, but...

> I don't know why or what business would use a speedtest in a prod env
> any guarantees on future releases being run
> integration testing pipeline

You should definitely build your own container (with daily! rebuilds) in your trusted environment and not pull from third party docker hub for your production environment.

**Comment by ondrejmo** [comment]
1) I know about the possibility of using image hashes as tags, but I don't want to do that, that's why I opened this issue (it needlesly obfuscates the configuration)
2) Here is public production instance that is at least based on the same source https://speedtest.cesnet.cz/
3) If I trust someones code I see no problem in using their `Dockerfile` and/or recently built image. As for rebuilding images daily, that's just not reasonable for a personal project, in larger coporate environment it would make sense, however in my current situation it would require singnificantly more resources tha the production containers do.

**Comment by adolfintel** [comment]
@callowaylc You are absolutely right, but calm down, there's no need to call me names.

This was my first time using docker, I didn't want to risk messing up the master branch, so I created a separate branch that is only updated when a new version or an important fix is released.
You won't get an update for every PR or minor change in the master branch so it's safe to use the latest image.

At this point I think it makes sense to merge it into the master branch and have tagged releases for docker as you all suggested, and I will do it when I have time (I'm currently working on another project which is why I haven't been very active, plus some personal issues).

**Comment by adolfintel** [comment]
I've updated the master branch with all the docker files. I did a quick test and it didn't seem to break anything. I'll update the docker hub image soon.

**Comment by adolfintel** [comment]
Done, docker releases will be tagged from now on.
Latest now builds from the master branch.

**Comment by stavros-k** [comment]
Tags on dockerhub still looks empty...
