### ISSUE TITLE
Self host speedtest server deployed with Docker Bug

### ISSUE THREAD

**Issue by gkl1368** [librespeed/speedtest#405]
I deployed this speedtest with docker in frontend and backend mode. But the webui always shows: No servers available

![image](https://user-images.githubusercontent.com/12904884/109225168-e35bbe00-77f7-11eb-8928-b88374ca757f.png)

The same servers.json is worked ok with speedtest-cli.

**Comment by gkl1368** [comment]
I found one bug, the backend only support port 80

**Comment by adolfintel** [comment]
Can you check the syntax of your servers.json file? Make sure it matches this https://github.com/librespeed/speedtest/blob/docker/doc.md#frontend-mode

About the backend, you should be able to change the port with the WEBPORT variable and the -p portA:portB argument when launching the container. Docker images usually run on port 80 because it's typical to put them behind some kind of reverse proxy for HTTPS (and other things).

**Comment by gkl1368** [comment]
> Can you check the syntax of your servers.json file? Make sure it matches this https://github.com/librespeed/speedtest/blob/docker/doc.md#frontend-mode
> 
> About the backend, you should be able to change the port with the WEBPORT variable and the -p portA:portB argument when launching the container. Docker images usually run on port 80 because it's typical to put them behind some kind of reverse proxy for HTTPS (and other things).

I mean in the servers.json, the server can't use like http://ipv4 address:port or http://ipv6 address:port

**Comment by gkl1368** [comment]
> Can you check the syntax of your servers.json file? Make sure it matches this https://github.com/librespeed/speedtest/blob/docker/doc.md#frontend-mode
> 
> About the backend, you should be able to change the port with the WEBPORT variable and the -p portA:portB argument when launching the container. Docker images usually run on port 80 because it's typical to put them behind some kind of reverse proxy for HTTPS (and other things).

I solved it with change WEBPORT variable, but now I face CORS policy problem.

**Comment by adolfintel** [comment]
Can you explain your setup? You're setting up a frontend that connects to what?

**Comment by gkl1368** [comment]
> Can you explain your setup? You're setting up a frontend that connects to what?

![image](https://user-images.githubusercontent.com/12904884/109308281-c1f0e580-787c-11eb-93e2-cb33936d9d6d.png)
you can see my screenshot. port 6688 is frontend and port 15560 is backend. 
When I do the speedtest, it doesn't show the result information.

**Comment by adolfintel** [comment]
I'll try replicating your problem when I'm on my docker machine and get back to you in a day or so

**Comment by gkl1368** [comment]
> I'll try replicating your problem when I'm on my docker machine and get back to you in a day or so

It show the results picture when I update new docker image today. But It still show "Access-Control-Allow-Origin" error.

**Comment by adolfintel** [comment]
Hello again,
I tried replicating your setup and it worked without problems. I've updated the documentation to make it a bit easier, but here's what I did:

Start a backend server on port 15560:
```
docker run -e MODE=backend -e WEBPORT=15560 -p 15560:15560 -it adolfintel/speedtest
```

Create a custom servers.json file in the current directory:
```json
[
    {
        "name": "Local server on port 15560",
        "server" :"http://localhost:15560/",
        "dlURL" :"garbage.php",
        "ulURL" :"empty.php",
        "pingURL" :"empty.php",
        "getIpURL" :"getIP.php"
    }
]
```

Start the frontend server with the custom servers.json on port 6688:
```
docker run -e MODE=frontend -e TELEMETRY=true -e ENABLE_ID_OBFUSCATION=true -e PASSWORD="yourPasswordHere" -e WEBPORT=6688 -v $(pwd)/servers.json:/servers.json -p 6688:6688 -it adolfintel/speedtest
```

Hope that helps.

**Comment by littlef0x** [comment]
Apologize for replying a closed issue. I've encountered the same problem.

I'm not quite sure but I think the method above may note work since the two docker containers do not share the same network. And thus the 'localhost' for frontend is not the same as the backend. I've tested it and got this in the frontend container:
```
# curl localhost:15560/getIP.php
curl: (7) Failed to connect to localhost port 15560: Connection refused
```

So what I did is to use --network=host for both containers. server.json is exactly the same as above. And I could access the backend in the frontend container.
```
# curl localhost:15560/getIP.php
{"processedString":"::1 - localhost IPv6 access","rawIspInfo":""}
# curl 127.0.0.1:15560/getIP.php
{"processedString":"127.0.0.1 - localhost IPv4 access","rawIspInfo":""}
```
However, the web UI still cannot find the backend. And there's no log output in the backend container. I also tried to use port redirection and public IP, which did not work, either. The port is open in firewall and the backend is accessable via curl. Both the frontend and backend is HTTP.

I also tried a public test server with the same frontend container, and the web UI worked as expected. So I think there should be something wrong with the backend container. Here's the log of the backend container.
```
$ docker logs -f librespeed-backend
+ rm -rf '/var/www/html/*'
+ cp /speedtest/speedtest.js /speedtest/speedtest_worker.js /var/www/html/
+ cp /speedtest/favicon.ico /var/www/html/
+ '[' backend == standalone ']'
+ '[' backend == backend ']'
+ cp -r /speedtest/backend/empty.php /speedtest/backend/garbage.php /speedtest/backend/getIP.php /speedtest/backend/getIP_ipInfo_apikey.php /speedtest/backend/getIP_util.php /var/www/html
+ '[' '!' -z '' ']'
+ '[' backend == frontend ']'
+ '[' backend == standalone ']'
+ [[ false == \t\r\u\e ]]
+ chown -R www-data /var/www/html/empty.php /var/www/html/favicon.ico /var/www/html/garbage.php /var/www/html/getIP.php /var/www/html/getIP_ipInfo_apikey.php /var/www/html/getIP_util.php /var/www/html/speedtest.js /var/www/html/speedtest_worker.js
+ '[' 15560 '!=' 80 ']'
+ sed -i 's/^Listen 80$/Listen 15560/g' /etc/apache2/ports.conf
+ sed -i 's/*:80>/*:15560>/g' /etc/apache2/sites-available/000-default.conf
+ echo 'Done, Starting APACHE'
Done, Starting APACHE
+ apache2-foreground
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 107.172.110.212. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 107.172.110.212. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 13 07:59:54.349991 2022] [mpm_prefork:notice] [pid 15] AH00163: Apache/2.4.52 (Debian) PHP/7.4.28 configured -- resuming normal operations
[Wed Apr 13 07:59:54.354306 2022] [core:notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'
```

This problem occured for multiple servers. The OS is Ubuntu 20.04.4 for all of them.
