### ISSUE TITLE
Display Public IP

### ISSUE THREAD

**Issue by chanty-kh** [librespeed/speedtest#407]
First, I am not a programmer :)

We are deploying the speedtest in our LAN. The page will display our LAN IP on the speedtest result.
Is it possible to display public ip too ? 
FYI: CLI to get the public ip is: "curl -s http://whatismyip.akamai.com/"

Thanks so much

**Comment by adolfintel** [comment]
The test shows the IP from which the server receives the connection, so if you're inside the local network it will show your local address and not your public one, because it doesn't go through the internet.
If you want to show it anyway the easiest way would be to embed that link in the page using an iframe, like this:
<iframe src="http://whatismyip.akamai.com/" style="border:none; width:10em; height:2em"></iframe>
