### ISSUE TITLE
New mirror in Iran

### ISSUE THREAD

**Issue by FakeShell** [librespeed/speedtest#444]
Hey
I submitted a server in Iran/Tehran yesterday. I'm submitting another one in Ghom today.
https://fastme.ir
You can access everything here and add it to the server list.
My contact email is fakeshell.bardia.tech
Its hosted and sponsored by Bardia Moshiri. (https://bardia.tech)
Thanks.

**Comment by EvansFix** [comment]
servers is down

**Comment by BardiaMGTGC** [comment]
It was down for maintenance for 2 hours we were optimizing services and upgrading server resources
Its up and running again
Thanks

**Comment by Perflyst** [comment]
Thanks! It's now available on librespeed.org

Can you please check why getIP is not fully working? ISP information etc is missing: https://fastme.ir/backend/getIP.php?isp=true

Much likely the request to ipinfo.io is not working. Can you check with curl if you can connect to ipinfo.io?
If so, please check if `allow_url_fopen` in your PHP settings is enabled.

**Comment by BardiaMGTGC** [comment]
It's because ipinfo.io is blocked in Iran and cannot be accessed.
If there are any alternatives tell me and i'll apply it.

Both servers i own in Iran which i contributed (this issue applies to all ips in Iran) gives me a google access deny as the output.

<title>Error 403 (Forbidden)!!1</title>
  <p>Your client does not have permission to get URL <code>/</code> from this server.  <ins>That’s all we know.</ins>
