### ISSUE TITLE
Symmetric Speed Test Option.

### ISSUE THREAD

**Issue by Lavakara** [librespeed/speedtest#451]
Feature request to perform upload and download simultaneously.

We use  Librespeed to test enterprise leaseline and MPLS  circuits. Being leaseline, ISP commints symmetric bandwidth(1:1). But most of the time there will be throughput issues. A option to test download and upload simultaneously will be usefull here.

Is there's any way we can perform download and upload tests simultaneously with slight change in code?

**Comment by adolfintel** [comment]
It's not something that we have right now, but you can jury rig something together fairly easy.
The easiest thing to do would be to make a custom frontend where the start button actually starts 2 tests simultaneously, one that only does download, and one that only does upload.
If you do this, you'll also have to change the number of concurrent streams for each test (xhr_dlMultistream and xhr_ulMultistream parameters), since the browser has a limit of 6 concurrent connections and by default the download test uses 6 and the upload test uses 3.

**Comment by Lavakara** [comment]
> The "proper" way would be to add a test for this in speedtest_worker.js

Thank you. Will try this.

**Comment by ValZapod** [comment]
It is strange that you do not have it. After all how can you saturate 2 gbit of Gigabyte Ethernet? And wifi is supposed to be only half duplex...
