### ISSUE TITLE
Fowl language in application

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [librespeed/speedtest#473]
## Description
The the fowl language in "No Flash, No Java, No Websocket, No **Bullshit**." is not appropriate.

## Why it should be implemented
Many of us can't use the application on our parent's devices, in public, or at work with this present. That is, it does more harm than good.

Thank you.

**Comment by SubMGRru** [comment]
As for me, this is not critical and appropriate in this case.
It's hard for me to imagine people who can't use such a cool solution like LibreSpeed just because of one word💆
this phrase is found only on the repository page, it is not in the application itself, so you can not worry and feel free to use the application in front of your parents😉

**Comment by Technetium1** [comment]
Especially since it's only in the repo and not the program this is a non-problem to me. That said it's still not exactly the most work-friendly phrasing, so they do have a point there. It could probably be said in a better way.

**Comment by shandrew** [comment]
A bull is not a fowl. Get that chip off your shoulder. This is bovine language, not fowl.

**Comment by Linerly** [comment]
…why not change it to “BS”

**Comment by zenflow** [comment]
> It's hard for me to imagine people who can't use such a cool solution like LibreSpeed just because of one word💆

Well, I imagine it depends on the word, I don't think "bullshit" is usually considered very offensive

@ae5960e8-a6fc-491f-b252-898ecf59af95 If anyone objects to you using this because of the word, just tell them that's bullshit. Problem solved. JK
But honestly if you're that bothered by it, just make a PR to change it to BS.. I doubt anyone would have a problem with that
